### ISSUE TITLE
core dumped with mindspore serving 1.5.0

### ISSUE THREAD

**Issue by kaierlong** [mindspore-ai/serving#1]
environment

> Ubuntu Server 20.04 x86_64
> RTX 3090 * 4
> Python 3.8.10
> CUDA 11.1.0
> cuDNN 8.0.5
> NCCL 2.8.4
> TensorRT 7.2.2
> MindSpore 1.5.0
> MindSpore Serving 1.5.0

install

```shell
pip3 install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.5.0/MindSpore/gpu/x86_64/cuda-11.1/mindspore_gpu-1.5.0-cp38-cp38-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple
pip3 install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.5.0/Serving/x86_64/mindspore_serving-1.5.0-cp38-cp38-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple
```

test mindspore serving
`python3 -c "from mindspore_serving import server"`

test failed and the output as below:
```
x free(): invalid pointer
Aborted (core dumped)
```

any help for this error?

**Comment by kaierlong** [comment]
mindspore install is ok.

test mindspore
`python3 -c "import mindspore;mindspore.run_check()"`

test output
```shell
MindSpore version: 1.5.0
The result of multiplication calculation is correct, MindSpore has been installed successfully!
```

**Comment by cxl-ll** [comment]
Hello users, I have checked that the python you are using is version 3.8.10. Currently, only 3.7.5 and 3.9.0 versions are supported, so I suggest you change the version to try.

**Comment by kaierlong** [comment]
@cxl-ll Thank you! I wiil have a try.

**Comment by cxl-ll** [comment]
This problem has been fixed in the latest Python 3.8 release package of MindSpore Serving version 1.5. You can use your previous installation link to install the latest package.

```text
pip3 install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.5.0/Serving/x86_64/mindspore_serving-1.5.0-cp38-cp38-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple
```

[bugfix link](https://github.com/mindspore-ai/serving/commit/a0639c373926b600acc22f10c843807073ee91c6)

**Comment by cxl-ll** [comment]
@kaierlong If the problem has been resolved, please close it. Thank you.

**Comment by kaierlong** [comment]
@cxl-ll 
The lastest Python 3.8 package of MindSpore Serving version 1.5 is OK.
Thank you!
